# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources (README.md file)
- Happy learning!

In [1]:
# import numpy and pandas
import numpy as np
import pandas as pd
import pymysql
from sqlalchemy import create_engine

# Challenge 1 - Index Functions

In this challenge, we will practice the advanced functions introduced in the lesson. However, before we start, we will load and evaluate our dataset. 

Load the dataset admissions predict in the Ironhack database.

In [2]:
# Your code
driver = 'mysql+pymysql'
ip = '35.239.232.23'
username = 'ironhacker_read'
password = 'ir0nhack3r'
db = 'admission_predict'

cs  = f'{driver}://{username}:{password}@{ip}/{db}'
engine = create_engine(cs)
Ssql = 'SELECT * FROM admission_predict '
adm = pd.read_sql(Ssql,engine)

Remove trailing spaces at the end of the column names

In [3]:
# Your code
adm.rename(columns=lambda x: x.strip(), inplace = True)

Let's evaluate the dataset by looking at the `head` function.

In [4]:
# Your code here:
adm.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,316,104,3,3,3.5,8,1,0.72
2,3,322,110,3,3.5,2.5,8.67,1,0.8
3,4,314,103,2,2,3,8.21,0,0.65
4,5,330,115,5,4.5,3,9.34,1,0.9

Before beginning to work with this dataset and evaluating graduate admissions data, we will verify that there is no missing data in the dataset. Do this in the cell below.

In [5]:
# Your code here:
adm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 385 entries, 0 to 384
Data columns (total 9 columns):
Serial No.           385 non-null int64
GRE Score            385 non-null int64
TOEFL Score          385 non-null int64
University Rating    385 non-null int64
SOP                  385 non-null object
LOR                  385 non-null object
CGPA                 385 non-null object
Research             385 non-null int64
Chance of Admit      385 non-null object
dtypes: int64(5), object(4)
memory usage: 27.1+ KB

Interestingly, there is a column that uniquely identifies the applicants. This column is the serial number column. Instead of having our own index, we should make this column our index. Do this in the cell below. Keep the column in the dataframe in addition to making it an index.

In [6]:
# Your code here:
adm.set_index(adm['Serial No.'], drop = True)

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
Serial No.,,,,,,,,,
1,1,337,118,4,4.5,4.5,9.65,1,0.92
2,2,316,104,3,3,3.5,8,1,0.72
3,3,322,110,3,3.5,2.5,8.67,1,0.8
4,4,314,103,2,2,3,8.21,0,0.65
5,5,330,115,5,4.5,3,9.34,1,0.9
6,6,321,109,3,3,4,8.2,1,0.75
7,7,308,101,2,3,4,7.9,0,0.68
8,8,302,102,1,2,1.5,8,0,0.5
9,9,323,108,3,3.5,3,8.6,0,0.45
10,10,327,111,4,4,4.5,9,1,0.84
11,11,328,112,4,4,4.5,9.1,1,0.78
12,12,307,109,3,4,3,8,1,0.62
13,13,311,104,3,3.5,2,8.2,1,0.61
14,14,314,105,3,3.5,2.5,8.3,0,0.54
15,15,317,107,3,4,3,8.7,0,0.66
16,16,319,106,3,4,3,8,1,0.65
17,17,318,110,3,4,3,8.8,0,0.63
18,18,303,102,3,3.5,3,8.5,0,0.62
19,19,325,114,4,3,2,8.4,0,0.7
20,20,328,116,5,5,5,9.5,1,0.94
21,21,334,119,5,5,4.5,9.7,1,0.95
22,22,336,119,5,4,3.5,9.8,1,0.97
23,23,322,109,5,4.5,3.5,8.8,0,0.76
24,24,298,98,2,1.5,2.5,7.5,1,0.44
25,25,295,93,1,2,2,7.2,0,0.46
26,26,310,99,2,1.5,2,7.3,0,0.54
27,27,300,97,2,3,3,8.1,1,0.65
28,28,327,103,3,4,4,8.3,1,0.74
29,29,338,118,4,3,4.5,9.4,1,0.91
30,30,340,114,5,4,4,9.6,1,0.9
...,...,...,...,...,...,...,...,...,...
356,356,310,103,2,2.5,2.5,8.24,0,0.72
357,357,324,110,3,3.5,3,9.22,1,0.89
358,358,336,119,4,4.5,4,9.62,1,0.95
359,359,321,109,3,3,3,8.54,1,0.79
360,360,315,105,2,2,2.5,7.65,0,0.39
361,361,304,101,2,2,2.5,7.66,0,0.38
362,362,297,96,2,2.5,2,7.43,0,0.34
363,363,290,100,1,1.5,2,7.56,0,0.47
364,364,303,98,1,2,2.5,7.65,0,0.56
365,365,311,99,1,2.5,3,8.43,1,0.71
366,366,322,104,3,3.5,4,8.84,1,0.78
367,367,319,105,3,3,3.5,8.67,1,0.73
368,368,324,110,4,4.5,4,9.15,1,0.82
369,369,300,100,3,3,3.5,8.26,0,0.62
370,370,340,113,4,5,5,9.74,1,0.96
371,371,335,117,5,5,5,9.82,1,0.96
372,372,302,101,2,2.5,3.5,7.96,0,0.46
373,373,307,105,2,2,3.5,8.1,0,0.53
374,374,296,97,2,1.5,2,7.8,0,0.49
375,375,320,108,3,3.5,4,8.44,1,0.76
376,376,314,102,2,2,2.5,8.24,0,0.64
377,377,318,106,3,2,3,8.65,0,0.71
378,378,326,112,4,4,3.5,9.12,1,0.84
379,379,317,104,2,3,3,8.76,0,0.77
380,380,329,111,4,4.5,4,9.23,1,0.89
381,381,324,110,3,3.5,3.5,9.04,1,0.82
382,382,325,107,3,3,3.5,9.11,1,0.84
383,383,330,116,4,5,4.5,9.45,1,0.91
384,384,312,103,3,3.5,4,8.78,0,0.67
385,385,333,117,4,5,4,9.66,1,0.95

Turns out that `GRE Score` and `CGPA` also uniquely identify the data. Show this in the cell below.

In [7]:
# Your code here:
adm[['CGPA','GRE Score']]

     CGPA  GRE Score
0    9.65        337
1       8        316
2    8.67        322
3    8.21        314
4    9.34        330
5     8.2        321
6     7.9        308
7       8        302
8     8.6        323
9       9        327
10    9.1        328
11      8        307
12    8.2        311
13    8.3        314
14    8.7        317
15      8        319
16    8.8        318
17    8.5        303
18    8.4        325
19    9.5        328
20    9.7        334
21    9.8        336
22    8.8        322
23    7.5        298
24    7.2        295
25    7.3        310
26    8.1        300
27    8.3        327
28    9.4        338
29    9.6        340
..    ...        ...
355  8.24        310
356  9.22        324
357  9.62        336
358  8.54        321
359  7.65        315
360  7.66        304
361  7.43        297
362  7.56        290
363  7.65        303
364  8.43        311
365  8.84        322
366  8.67        319
367  9.15        324
368  8.26        300
369  9.74        340
370  9.82        335
371  7.96        302
372   8.1        307
373   7.8        296
374  8.44        320
375  8.24        314
376  8.65        318
377  9.12        326
378  8.76        317
379  9.23        329
380  9.04        324
381  9.11        325
382  9.45        330
383  8.78        312
384  9.66        333

[385 rows x 2 columns]

Replace the index with an index comprised of two columns - `GRE Score` and `CGPA`. Remove the columns from the dataset as well. Make sure to use `inplace=True`.

In [8]:
adm.set_index(['CGPA','GRE Score'], drop=False, inplace=True)

Now change the index back to a sequence starting at zero using the `reset_index` function. Make sure to use `inplace=True`.

In [14]:
# Your code here:
adm.reset_index(drop=True, inplace=True)
adm

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,316,104,3,3,3.5,8,1,0.72
2,3,322,110,3,3.5,2.5,8.67,1,0.8
3,4,314,103,2,2,3,8.21,0,0.65
4,5,330,115,5,4.5,3,9.34,1,0.9
5,6,321,109,3,3,4,8.2,1,0.75
6,7,308,101,2,3,4,7.9,0,0.68
7,8,302,102,1,2,1.5,8,0,0.5
8,9,323,108,3,3.5,3,8.6,0,0.45
9,10,327,111,4,4,4.5,9,1,0.84
10,11,328,112,4,4,4.5,9.1,1,0.78
11,12,307,109,3,4,3,8,1,0.62
12,13,311,104,3,3.5,2,8.2,1,0.61
13,14,314,105,3,3.5,2.5,8.3,0,0.54
14,15,317,107,3,4,3,8.7,0,0.66
15,16,319,106,3,4,3,8,1,0.65
16,17,318,110,3,4,3,8.8,0,0.63
17,18,303,102,3,3.5,3,8.5,0,0.62
18,19,325,114,4,3,2,8.4,0,0.7
19,20,328,116,5,5,5,9.5,1,0.94
20,21,334,119,5,5,4.5,9.7,1,0.95
21,22,336,119,5,4,3.5,9.8,1,0.97
22,23,322,109,5,4.5,3.5,8.8,0,0.76
23,24,298,98,2,1.5,2.5,7.5,1,0.44
24,25,295,93,1,2,2,7.2,0,0.46
25,26,310,99,2,1.5,2,7.3,0,0.54
26,27,300,97,2,3,3,8.1,1,0.65
27,28,327,103,3,4,4,8.3,1,0.74
28,29,338,118,4,3,4.5,9.4,1,0.91
29,30,340,114,5,4,4,9.6,1,0.9
...,...,...,...,...,...,...,...,...,...
355,356,310,103,2,2.5,2.5,8.24,0,0.72
356,357,324,110,3,3.5,3,9.22,1,0.89
357,358,336,119,4,4.5,4,9.62,1,0.95
358,359,321,109,3,3,3,8.54,1,0.79
359,360,315,105,2,2,2.5,7.65,0,0.39
360,361,304,101,2,2,2.5,7.66,0,0.38
361,362,297,96,2,2.5,2,7.43,0,0.34
362,363,290,100,1,1.5,2,7.56,0,0.47
363,364,303,98,1,2,2.5,7.65,0,0.56
364,365,311,99,1,2.5,3,8.43,1,0.71
365,366,322,104,3,3.5,4,8.84,1,0.78
366,367,319,105,3,3,3.5,8.67,1,0.73
367,368,324,110,4,4.5,4,9.15,1,0.82
368,369,300,100,3,3,3.5,8.26,0,0.62
369,370,340,113,4,5,5,9.74,1,0.96
370,371,335,117,5,5,5,9.82,1,0.96
371,372,302,101,2,2.5,3.5,7.96,0,0.46
372,373,307,105,2,2,3.5,8.1,0,0.53
373,374,296,97,2,1.5,2,7.8,0,0.49
374,375,320,108,3,3.5,4,8.44,1,0.76
375,376,314,102,2,2,2.5,8.24,0,0.64
376,377,318,106,3,2,3,8.65,0,0.71
377,378,326,112,4,4,3.5,9.12,1,0.84
378,379,317,104,2,3,3,8.76,0,0.77
379,380,329,111,4,4.5,4,9.23,1,0.89
380,381,324,110,3,3.5,3.5,9.04,1,0.82
381,382,325,107,3,3,3.5,9.11,1,0.84
382,383,330,116,4,5,4.5,9.45,1,0.91
383,384,312,103,3,3.5,4,8.78,0,0.67
384,385,333,117,4,5,4,9.66,1,0.95

# Challenge 2 - Advanced Functions

In this part of the lab, we would like to test complex conditions on the entire dataset at once. Let's start by finding the number of rows where the CGPA is higher than 9 and the student has conducted research.

In [10]:
# Your code here:

Now return all the rows where the CGPA is greater than 9 and the SOP score is less than 3.5. Find the mean chance of admit for these applicants.

In [11]:
# Your code here:

We would like to create a deciding factor column for each student. We standardize several columns and then pick the most important factor from a lookup table. If the standardized value is above 0.8, the student will be accepted.

We will start by creating a standardized column for `CGPA`, `GRE Score` and `LOR`. We will name these columns `CGPA_std`, `GRE_std`, and `LOR_std` respecively.

Recall that standardizing a column is done by subtracting the mean of the column from all observations in the column and then dividing each observation in the column by the column's standard deviation.

In the cell below, write a standardization function (a function that takes a column as input and returns a standardized column as output). Make sure to use the `numpy` versions of mean and standard deviation.

In [12]:
def standardize(col):
    # This function takes a column from a dataframe and returns a standardized column by subtracting the column's mean
    # and dividing by the column's standard deviation.
    
    # Your code here:

SyntaxError: unexpected EOF while parsing (<ipython-input-12-ee3135619f50>, line 5)

Now create the standardized columns `CGPA_std`, `GRE_std`, and `LOR_std` and add them to the `admissions` dataframe.

In [ ]:
# Your code here:

We will generate the decision choice at random using the code below. Please run the cell.

In [ ]:
# Run this code:

from random import choices
std_columns = ['CGPA_std', 'GRE_std', 'LOR_std']

decision_choice = choices(std_columns, k=admissions.shape[0])

Now create the deciding column using the `lookup` function. The lookup column is `decision_choice` found above. Call the column resulting from the lookup function `deciding_column` and add it to the `admissions` dataframe.

In [ ]:
# Your code here:

Create a column called `decision` in the `admissions` dataframe. Assign 1 to this column if the value of `deciding_column` is greater than 0.8 and 0 otherwise.

In [ ]:
# Your code here:

How many applicants will be accepted to the program using the decision column? Compute the result below.

In [ ]:
# Your code here:

# Challenge 3 - Method Chaining

To increase our coding efficiency, let's make a number of changes to our dataframe in one line of code.

In the cell below, remove all non character symbols from the column names, replace all spaces in column names to underscores, and change all upper case characters to lower case. Assign these new column values to `admissions.columns`.

In [ ]:
# Your code here:

In the cell below, give all student with a university rating of 4 or higher a 10 point boost on their GRE score and split the column into 4 bins using the `cut` function. Assign this new score to the variable `adjusted_gre`.

In [ ]:
# Your code here: